// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_7i5QrAzlKqPZYQXzIQPwLdfvH-dd0Aw',
    appId: '1:707410552477:web:f92237f365a08f62469674',
    messagingSenderId: '707410552477',
    projectId: 'online-c686f',
    authDomain: 'online-c686f.firebaseapp.com',
    storageBucket: 'online-c686f.appspot.com',
    measurementId: 'G-HSFQZDQRSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKWIfnZtyL9ilHWAa5c3XjlPgeJCX_y1Q',
    appId: '1:707410552477:android:edf8522f263ba96e469674',
    messagingSenderId: '707410552477',
    projectId: 'online-c686f',
    storageBucket: 'online-c686f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzPJWEFcSawAgxl7wZForMBgQzaiM8GJ8',
    appId: '1:707410552477:ios:b2f7477b05dc9f8c469674',
    messagingSenderId: '707410552477',
    projectId: 'online-c686f',
    storageBucket: 'online-c686f.appspot.com',
    iosBundleId: 'com.example.reverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzPJWEFcSawAgxl7wZForMBgQzaiM8GJ8',
    appId: '1:707410552477:ios:163fe83c02162c0f469674',
    messagingSenderId: '707410552477',
    projectId: 'online-c686f',
    storageBucket: 'online-c686f.appspot.com',
    iosBundleId: 'com.example.reverse.RunnerTests',
  );
}
